blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/AntoineArt/syncstation/blob/main/README.md
    about: Check the README and documentation for usage instructions and examples
  - name: Discussions
    url: https://github.com/AntoineArt/syncstation/discussions
    about: Ask questions and discuss ideas with the community